source 'http://gemcutter.org'

gem 'rack', '1.1.0'
gem 'sinatra', '1.0', :require => 'sinatra/base'
gem 'haml', '2.2.19'
gem 'builder', '2.1.2'
gem 'activesupport', '2.3.5', :require => 'active_support'
gem 'activerecord', '2.3.5', :require => 'active_record'
gem 'sinatra-bundles', '0.2.0', :require => 'sinatra/bundles'
gem 'darkhelmet-sinatra_more', '0.3.36', :require => nil
gem 'acts_as_taggable_on_steroids', '1.2', :require => nil
gem 'RedCloth', '4.2.2'
gem 'crack', '0.1.6'
gem 'rest-client', '1.3.1', :require => 'restclient'
gem 'tzinfo', '0.3.16'
gem 'rainpress', '1.0.0'
gem 'packr', '3.1.0'
gem 'hpricot', '0.8.2'
gem 'sanitize', '1.2.0'
gem 'texticle', '1.0.2'
gem 'term_extraction', '0.1.7'
gem 'hashie', '0.1.8'
gem 'tilt', '0.8'
gem 'will_paginate', '2.3.12'
gem 'pg', '0.8.0'
gem 'newrelic_rpm', '2.10.5'