source 'http://gemcutter.org'

gem 'rack', '1.1.0'
gem 'sinatra', '1.0.a', :require_as => 'sinatra/base'
gem 'haml'
gem 'builder'
gem 'i18n'
gem 'activerecord', '2.3.5', :require_as => 'active_record'
gem 'activesupport', '2.3.5', :require_as => 'active_support'
gem 'sinatra-bundles', :require_as => 'sinatra/bundles'
gem 'darkhelmet-sinatra_more', '>= 0.3.36'
gem 'acts_as_taggable_on_steroids', '>= 1.2'
gem 'RedCloth'
gem 'crack'
gem 'rest-client', :require_as => 'restclient'
gem 'tzinfo'
gem 'rainpress'
gem 'packr'
gem 'hpricot'
gem 'texticle'
gem 'term_extraction'
gem 'addressable'
gem 'darkhelmet-sanitize', :require_as => 'sanitize'
gem 'hashie'
gem 'httparty'
gem 'tilt'
gem 'thor', '>= 0.11.8'
gem 'feedzirra'
gem 'httpclient'
gem 'pg'
# gem 'newrelic_rpm'